include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = QuickSearchPrefs

QuickSearchPrefs_FILES = ICRQSRootListController.m
QuickSearchPrefs_FRAMEWORKS = UIKit
QuickSearchPrefs_PRIVATE_FRAMEWORKS = Preferences
QuickSearchPrefs_INSTALL_PATH = /Library/PreferenceBundles
QuickSearchPrefs_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
